/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenzhoundgui;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Thayer
 */
public class SplashForm extends javax.swing.JFrame {

    /**
     * Creates new form SplashForm
     */
    public static boolean finished = false;
    
    public SplashForm() {
        this.setUndecorated(true);
        initComponents();        
        this.setSize(splashLabel.size());        
        this.setLocationRelativeTo(null);
        Thread t = new Thread( () -> {
            this.show();
            try {
                Thread.sleep(6000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SplashForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.hide();
            finished = true;
        });
        t.run();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        splashLabel = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setResizable(false);

        splashLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        splashLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lenzhoundgui/res/splash.png"))); // NOI18N
        splashLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashLabel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashLabel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel splashLabel;
    // End of variables declaration//GEN-END:variables
}
